### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by anatoliyRodkin** [usedesk/Android_SDK#12]
Если после открытия экрана чата не дожидаясь полной загрузки страницы свернуть приложение, то произойдет краш.
_Так выглядит код моей активности с чатом:_

```
public class UsedeskChatActivity extends PassphraseRequiredActionBarActivity implements IUsedeskOnFileClickListener {

    @Override
    public void onBackPressed() {
        FragmentManager fragmentManager = getSupportFragmentManager();
        if (fragmentManager.getBackStackEntryCount() > 1) {
            Fragment fragment = fragmentManager.getFragments().get(0);
            if (fragment instanceof UsedeskFragment && ((UsedeskFragment) fragment).onBackPressed()) {
                return;
            }
            fragmentManager.popBackStack();
        } else if (fragmentManager.getFragments().get(0) instanceof UsedeskFragment &&
                ((UsedeskFragment) fragmentManager.getFragments().get(0)).onBackPressed()) {
            return;
        } else {
            finish();
        }
    }

    @Override
    protected void onCreate(Bundle savedInstanceState, boolean ready) {
        UsedeskChatSdk.init(this);
        setContentView(R.layout.container);
        UsedeskChatScreen f = UsedeskChatScreen.newInstance();
        getSupportFragmentManager().beginTransaction()
                .addToBackStack(f.getClass().getName() + ":" + f.hashCode())
                .replace(R.id.flContainer, f, "UsedeskChat")
                .commit();
    }

    @Override
    public void onFileClick(@NonNull UsedeskFile usedeskFile) {
        UsedeskShowFileScreen sfs = UsedeskShowFileScreen.newInstance(usedeskFile);
        getSupportFragmentManager().beginTransaction()
                .setCustomAnimations(
                        R.anim.nav_default_enter_anim,  // enter
                        R.anim.nav_default_exit_anim,  // exit
                        R.anim.nav_default_pop_enter_anim,  // popEnter
                        R.anim.nav_default_pop_exit_anim// popExit
                )
                .addToBackStack(sfs.getClass().getName() + ":" + sfs.hashCode())
                .replace(getSupportFragmentManager().getFragments().get(0).getId(), sfs)
                .commit();
    }
}
```
_Краш лог:_

**E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.exscudo.channels.int, PID: 31272
    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1844)
        at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1967)
        at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:305)
        at ru.usedesk.chat_gui.chat.ChatNavigation.navigateToRoot$lambda-3(ChatNavigation.kt:54)
        at ru.usedesk.chat_gui.chat.ChatNavigation.lambda$C78USWnbDQs1H3gi7xgmIczvXSo(Unknown Source:0)
        at ru.usedesk.chat_gui.chat.-$$Lambda$ChatNavigation$C78USWnbDQs1H3gi7xgmIczvXSo.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8057)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)**
        
Версия Usedesk SDK: 3.9.0
Использую только GUI

**Comment by Uncreated** [comment]
Обновись до v3.10.8, там такой проблемы нет
