### ISSUE TITLE
Краш в MessagesAdapter

### ISSUE THREAD

**Issue by iyakovlev** [usedesk/Android_SDK#15]
sdk 3.11.1, используем chat gui
Нестабильно встречается при hide/show фрагмента чата
```
Fatal Exception: java.lang.IllegalArgumentException: Requested element count -1 is less than zero.
       at kotlin.sequences.SequencesKt___SequencesKt.drop(_Sequences.kt:403)
       at ru.usedesk.chat_gui.chat.messages.adapters.MessagesAdapter.updateFloatingDate$lambda-7(MessagesAdapter.java:96)
       at ru.usedesk.chat_gui.chat.messages.adapters.MessagesAdapter$$InternalSyntheticLambda$3$0f089bf8925961cd1e1b6a2830f61c6f72f41edbdeae4b8b3c607bc67674893c$0.run$bridge(MessagesAdapter.java:9)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6864)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by Uncreated** [comment]
Спасибо, что поделились информацией об ошибке. Действительно, поведение в таком кейсе нестабильно. Мы выпустим новую версию с исправлением до конца недели.

Как только будет готово, дополнительно напишем.

**Comment by Uncreated** [comment]
Привет! Простите, что неверно сориентировали по срокам фикса. Уже исправили в [v3.11.8](https://github.com/usedesk/Android_SDK/releases/tag/3.11.8).
