### ISSUE TITLE
Падение при передаче clientToken с зарезервированными символами

### ISSUE THREAD

**Issue by GvinPin47** [usedesk/Android_SDK#16]
При создании конфигурации `UsedeskChatConfiguration` и указания clientToken содержащим pathSeparator (/) падает ошибка `java.lang.IllegalArgumentException: File UsedeskMessagesRepository{mega/Key}.xml contains a path separator`

Планируются ли исправления данного кейса?

трейс: 

```
W/System.err:     at ru.usedesk.chat_sdk.data.repository.messages.MessagesRepository.getSharedPreferences(MessagesRepository.kt:32)
W/System.err:     at ru.usedesk.chat_sdk.data.repository.messages.MessagesRepository.initIfNeeded(MessagesRepository.kt:129)
W/System.err:     at ru.usedesk.chat_sdk.data.repository.messages.MessagesRepository.getDraft(MessagesRepository.kt:96)
W/System.err:     at ru.usedesk.chat_sdk.domain.CachedMessagesInteractor$1.invokeSuspend(CachedMessagesInteractor.kt:32)
W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/System.err:     at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
W/System.err:     at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
W/System.err:     at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
W/System.err:     at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
W/System.err:     at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
W/System.err:     at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
W/System.err:     at ru.usedesk.chat_sdk.domain.CachedMessagesInteractor.<init>(CachedMessagesInteractor.kt:30)
W/System.err:     at ru.usedesk.chat_sdk.di.ChatModule.provideCachedMessagesInteractor(ChatModule.kt:115)
W/System.err:     at ru.usedesk.chat_sdk.di.ChatModule_ProvideCachedMessagesInteractorFactory.provideCachedMessagesInteractor(ChatModule_ProvideCachedMessagesInteractorFactory.java:49)
W/System.err:     at ru.usedesk.chat_sdk.di.ChatModule_ProvideCachedMessagesInteractorFactory.get(ChatModule_ProvideCachedMessagesInteractorFactory.java:36)
W/System.err:     at ru.usedesk.chat_sdk.di.ChatModule_ProvideCachedMessagesInteractorFactory.get(ChatModule_ProvideCachedMessagesInteractorFactory.java:13)
W/System.err:     at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
W/System.err:     at ru.usedesk.chat_sdk.di.ChatModule_ProvideChatInteractorFactory.get(ChatModule_ProvideChatInteractorFactory.java:41)
W/System.err:     at ru.usedesk.chat_sdk.di.ChatModule_ProvideChatInteractorFactory.get(ChatModule_ProvideChatInteractorFactory.java:14)
W/System.err:     at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
W/System.err:     at ru.usedesk.chat_sdk.di.DaggerChatComponent.getChatInteractor(DaggerChatComponent.java:109)
W/System.err:     at ru.usedesk.chat_sdk.di.InstanceBoxUsedesk.<init>(InstanceBoxUsedesk.kt:31)
W/System.err:     at ru.usedesk.chat_sdk.UsedeskChatSdk.init(UsedeskChatSdk.kt:38)
```

**Comment by Uncreated** [comment]
Приветствую. 
Токен клиента генерируется сервером и не должен содержать такие символы. Убедитесь, что передаёте в конфигурации только правильный токен.
