### ISSUE TITLE
Crash on UsedeskSdk.initChat

### ISSUE THREAD

**Issue by remain4life** [usedesk/Android_SDK#2]
Добрый день! Использую ваш SDK через Maven, последняя версия 1.0.7. При повторном вызове метода `UsedeskSdk.initChat()` приложение падает с такой ошибкой:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Long.equals(java.lang.Object)' on a null object reference
        at ru.usedesk.sdk.internal.domain.interactor.ChatInteractor.init(ChatInteractor.java:278)
        at ru.usedesk.sdk.external.UsedeskChat.init(UsedeskChat.java:28)
        at ru.usedesk.sdk.external.UsedeskSdk$UsedeskChatBox.<init>(UsedeskSdk.java:135)
        at ru.usedesk.sdk.external.UsedeskSdk.initChat(UsedeskSdk.java:49)
```
Чат освобождал через `UsedeskSdk.releaseChat()`. Пробовал заново запускать установку конфигурации `UsedeskSdk.setUsedeskConfiguration()` перед вызовом `UsedeskSdk.initChat()`, ошибка повторяется.

**Comment by remain4life** [comment]
Данные для установки конфигурации использовал тестовые из сэмпла:

```
public void setUsedeskConfig() {
        Configuration configuration = new Configuration("153712",
                "android_sdk@usedesk.ru",
                "https://pubsub.usedesk.ru:1992",
                "https://secure.usedesk.ru",
                "4",
                "11eb3f39dec94ecf0fe4a80349903e6ad5ce6d75",
                "Иван Иванов",
                "88005553535",
                "777",
                false,
                false,
                true);
        LogUtil.d(CHAT_TAG, "Config for chat: " + configuration);
        initUsedeskConfiguration(configuration);
    }


    private void initUsedeskConfiguration(@NonNull Configuration configuration) {
        UsedeskSdk.setUsedeskConfiguration(new UsedeskConfiguration(configuration.getCompanyId(),
                        configuration.getEmail(),
                        configuration.getUrl(),
                        configuration.getOfflineFormUrl(),
                        configuration.getClientName(),
                        getLong(configuration.getClientPhoneNumber()),
                        getLong(configuration.getClientAdditionalId())
                )
        );

        UsedeskConfiguration usedeskConfiguration = UsedeskSdk.getUsedeskConfiguration();
        LogUtil.d(CHAT_TAG,"Using config: " + (usedeskConfiguration == null ? null : new Configuration(usedeskConfiguration)));

    }
```

При логировании заметил, что в конфигурации телефон и additionalId сохраняются как null, все остальные поля сохраняются корректно. Похоже, что именно из-за этого возникает ошибка при инициализации. Это может быть вызвано тем, что данные тестовые?

**Comment by Uncreated** [comment]
Привет.
Баг воспроизвёл, в скором времени исправлю.

**Comment by Uncreated** [comment]
Исправлено в версии 1.0.8
