### ISSUE TITLE
Ошибка миграции

### ISSUE THREAD

**Issue by GvinPin47** [usedesk/Android_SDK#20]
При поднятии версии sdk с 3.11.10 до 4.1.2 возникает исключение:

`Fatal Exception: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter urlChatApi
       at ru.usedesk.chat_sdk.entity.UsedeskChatConfiguration.copy(:43)
       at ru.usedesk.chat_sdk.entity.UsedeskChatConfiguration.copy$default(:183)
       at ru.usedesk.chat_sdk.domain.ChatInteractor$onChatInited$2.invoke(ChatInteractor.kt:891)
       at ru.usedesk.chat_sdk.domain.ChatInteractor$onChatInited$2.invoke(ChatInteractor.kt:891)
       at ru.usedesk.chat_sdk.data.repository.configuration.UserInfoRepository$updateConfiguration$1.invokeSuspend(UserInfoRepository.kt:45)`

**Comment by nichvolod** [comment]
Fixed at 4.1.3 https://github.com/usedesk/Android_SDK/releases/tag/4.1.3
