### ISSUE TITLE
android.view.InflateException:

### ISSUE THREAD

**Issue by andrey30530** [usedesk/Android_SDK#24]
Hello usedesk team!

After updating from version 4.1.3 to 4.2.2 the following error appeared

<details>

<summary>Stacktrace</summary>

```
android.view.InflateException: Binary XML file line #4 in com.mypackage:layout/usedesk_view_player: Binary XML file line #4 in com.mypackage:layout/usedesk_view_player: Error inflating class <unknown>
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #4 in com.mypackage:layout/usedesk_view_player: Error inflating class <unknown>
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:742)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:894)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:849)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:462)
                                                                                                    	at ru.usedesk.common_gui.UsedeskBindingKt.inflateItem(UsedeskBinding.kt:46)
                                                                                                    	at ru.usedesk.common_gui.UsedeskBindingKt.inflateItem(UsedeskBinding.kt:27)
                                                                                                    	at ru.usedesk.chat_gui.chat.MediaPlayerAdapter.<init>(MediaPlayerAdapter.kt:44)
                                                                                                    	at ru.usedesk.chat_gui.chat.UsedeskChatScreen$mediaPlayerAdapter$2.invoke(UsedeskChatScreen.kt:35)
                                                                                                    	at ru.usedesk.chat_gui.chat.UsedeskChatScreen$mediaPlayerAdapter$2.invoke(UsedeskChatScreen.kt:34)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at ru.usedesk.chat_gui.chat.UsedeskChatScreen.getMediaPlayerAdapter$chat_gui_release(UsedeskChatScreen.kt:34)
                                                                                                    	at ru.usedesk.chat_gui.chat.messages.MessagesPage.init(MessagesPage.kt:205)
                                                                                                    	at ru.usedesk.chat_gui.chat.messages.MessagesPage.onViewCreated(MessagesPage.kt:75)
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
                                                                                                    	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8501)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
                                                                                                    Caused by: java.lang.ClassCastException: com.google.android.exoplayer2.ui.AspectRatioFrameLayout cannot be cast to androidx.media3.ui.AspectRatioFrameLayout
                                                                                                    	at androidx.media3.ui.PlayerView.<init>(PlayerView.java:390)
                                                                                                    	at androidx.media3.ui.PlayerView.<init>(PlayerView.java:306)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:742) 
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:894) 
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:849) 
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:543) 
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:462) 
                                                                                                    	at ru.usedesk.common_gui.UsedeskBindingKt.inflateItem(UsedeskBinding.kt:46) 
                                                                                                    	at ru.usedesk.common_gui.UsedeskBindingKt.inflateItem(UsedeskBinding.kt:27) 
                                                                                                    	at ru.usedesk.chat_gui.chat.MediaPlayerAdapter.<init>(MediaPlayerAdapter.kt:44) 
                                                                                                    	at ru.usedesk.chat_gui.chat.UsedeskChatScreen$mediaPlayerAdapter$2.invoke(UsedeskChatScreen.kt:35) 
                                                                                                    	at ru.usedesk.chat_gui.chat.UsedeskChatScreen$mediaPlayerAdapter$2.invoke(UsedeskChatScreen.kt:34) 
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
                                                                                                    	at ru.usedesk.chat_gui.chat.UsedeskChatScreen.getMediaPlayerAdapter$chat_gui_release(UsedeskChatScreen.kt:34) 
                                                                                                    	at ru.usedesk.chat_gui.chat.messages.MessagesPage.init(MessagesPage.kt:205) 
                                                                                                    	at ru.usedesk.chat_gui.chat.messages.MessagesPage.onViewCreated(MessagesPage.kt:75) 
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272) 
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943) 
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845) 
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782) 
                                                                                                    	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8501) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878) 
```

</details>

Is there a fix planned?

**Comment by nichvolod** [comment]
Hi there! Thank you for reaching out to us.

We weren't able to reproduce this issue. We need some additional information.

Can you provide the version of ExoPlayer used in your project? What else is different in the dependencies of your project compared to our sample app? Additionally, the OS version and device would be helpful

**Comment by andrey30530** [comment]
Hi there! Thanks for your reply.

The problem was with the ExoPlayer version. After switching to the android.media3 package, everything started working fine.
